[build]
builder = "nixpacks"
buildCommand = "chmod +x railway-build.sh && ./railway-build.sh"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
NODE_VERSION = "18.19.0"
