services:
  - type: web
    name: analyseur-interventions
    env: php
    buildCommand: './render-build.sh'
    startCommand: 'heroku-php-apache2 public/'
    runtime: node
    nodeVersion: 18.19.0
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: "Analyseur d'Interventions"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: NODE_OPTIONS
        value: '--max_old_space_size=4096'
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/database
      sizeGB: 1
